version: "3.9"

services:
  mlflow:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    container_name: mlflow
    working_dir: /app
    volumes:
      - ./mlruns:/mlruns
    ports:
      - "5000:5000"

  api:
    build: .
    container_name: mlops-api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    volumes:
      - ./mlruns:/mlruns
      - ./data:/app/data
